name: 'slack upload file'
description: 'upload file to slack'
author: 'MeilCli'
branding:
  icon: arrow-up
  color: blue
inputs:
  slack_token:
    description: 'Slack token, must has files:write permission'
    required: true
  slack_api_url:
    description: 'Custom slack api url'
  channels:
    description: 'Comma-separated list of channel names or IDs where the file will be shared.'
  content:
    description: 'File contents via a POST variable. If omitting this parameter, you must provide a file.'
  file_path:
    description: 'File contents via multipart/form-data. If omitting this parameter, you must submit content.'
  file_name:
    description: 'Filename of file.'
  file_type:
    description: 'A file type identifier.'
  initial_comment:
    description: 'The message text introducing the file in specified channels.'
  thread_ts:
    description: 'Provide another message`s ts value to upload this file as a reply. Never use a reply`s ts value; use its parent instead.'
  title:
    description: 'Title of file.'
  retries:
    description: 'max API retry count. default retries is 3'
outputs:
  response:
    description: 'the api response'
runs:
  using: 'node12'
  main: 'dist/index.js'
