on:
  workflow_call:

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        with:
          github-token: ${{ secrets.MEILCLI_BOT }}
          script: |
            github.rest.pulls.createReview(
              {
                pull_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                event: 'APPROVE'
              }
            )
