name: CI-PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/ci-base-build.yml
    permissions:
      contents: read
    secrets: inherit
  approve:
    uses: ./.github/workflows/ci-base-approve.yml
    permissions:
      pull-requests: read
    secrets: inherit
    needs: build
  merge:
    uses: ./.github/workflows/ci-base-merge.yml
    permissions: {}
    secrets: inherit
    needs: build
