name: Debug

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'post message as text file to slack'
        required: true
        default: 'Hello World!'
      delete_file_ids_before_upload:
        description: 'for post3 job argument'
        required: false
        default: ''

jobs:
  post1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo ${{ github.event.inputs.message }} > test1.txt'
      - run: 'echo ${{ github.event.inputs.message }} > test2.txt'
      - uses: ./
        id: upload_file
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'test*.txt'
          initial_comment: 'post by slack-upload-file'
  # test for issue 529
  post2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p testsrc/main
      - run: 'echo ${{ github.event.inputs.message }} > testsrc/main/test1.txt'
      - run: 'echo ${{ github.event.inputs.message }} > testsrc/main/test2.txt'
      - uses: ./
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'testsrc/main/test*.txt'
          file_type: 'text'
          initial_comment: 'post by slack-upload-file for testing issue 529'
  post3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo ${{ github.event.inputs.message }}${{ github.run_number }} > replacement_test.txt'
      - uses: ./
        id: slack_upload
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'replacement_test.txt'
          file_type: 'text'
          delete_file_ids_before_upload: ${{ github.event.inputs.delete_file_ids_before_upload }}
      - run: 'echo ${{ steps.slack_upload.outputs.uploaded_file_id }}'
