name: Report

on:
  workflow_run:
    workflows: ['CI-Master', 'CI-PR']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: sleep 10s
        name: wait for API&DB synchronized
      - name: Download artifact
        uses: dawidd6/action-download-artifact@d63b86af1b34672e53c440b1b83979861906bad7 # v24
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: result
      - name: Transform report file
        uses: MeilCli/common-lint-reporter/transformer/eslint@ad58e91c55e7f7f03cb05d57235816c4c31500dc # v2.0.12
        with:
          report_files: |
            eslint_report.json
      - name: Report lint result
        uses: MeilCli/common-lint-reporter@ad58e91c55e7f7f03cb05d57235816c4c31500dc # v2.0.12
        with:
          report_type: 'check_run'
          report_name: 'Lint Report'
